apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      labels:
        app: blue-deployment
    spec:
      containers:
      - name: udacity_capstone
        image: mryutran/udacity_capstone:latest
        ports:
         - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: webapp-service
spec:
  selector:
    app: blue-app
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
---
