apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udacity-capstone
  region: us-east-1

iam: 
  withOIDC: true

nodeGroups:
  - name: udacity-capstone
    instanceType: t2.small
    amiFamily: AmazonLinux2
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 80
    ssh: # enable SSH using SSM
      enableSsm: true
      