apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udacity_capstone_cluster
  region: us-west-1

nodeGroups:
  - name: udacity
    instanceType: t2.small
    amiFamily: AmazonLinux2
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: udacity
