apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone-service
spec:
  type: LoadBalancer
  selector:
    app: udacity-capstone
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
