version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.1.0
  aws-ecr: circleci/aws-ecr@7.2.0
  kubernetes: circleci/kubernetes@0.4.0
  shellcheck: circleci/shellcheck@3.1.1

jobs:
    run-lint:
      docker:
        # Use the same Docker base as the project
        - image: python:3.7.3-stretch
      working_directory: ~/repo

      steps:
        - checkout          
          # Download and cache dependencies
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "~/repo/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

        - run:
            name: install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              make install
              # Install hadolint
              wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint
        - save_cache:
            paths:
              - ./venv
            key: v1-dependencies-{{ checksum "~/repo/requirements.txt" }}

        # run lint!
        - run:
            name: run lint
            command: |
              . venv/bin/activate
              make lint 
    
    build-docker-image:
      docker:
        - image: python:3.7.3-stretch
      steps:
        - checkout
        - setup_remote_docker:
            version: 20.10.14
        - run:
           name: Build Docker Image
           command: |
            chmod +x build_docker.sh
            bash build_docker.sh
    
workflows:
  default:
    jobs:
      - shellcheck/check
      - run-lint:
          requires:
            - "shellcheck/check"
      - build-docker-image:
          requires:
            - "run-lint"
